# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YurufuwaManage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YurufuwaManage
  pod 'Gryphon', '~> 3.1'

  target 'YurufuwaManageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YurufuwaManageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
